### ISSUE TITLE
TrackRemoved Signal takes incorrect input

### ISSUE THREAD

**Issue by yashBhosale** [alexdelorenzo/mpris_server#2]
Hi, in https://github.com/alexdelorenzo/mpris_server/blob/master/mpris_server/tracklist.py the trackremoved signal inputs/outputs an array of object paths, when the spec https://specifications.freedesktop.org/mpris-spec/latest/Track_List_Interface.html says it's supposed to emit just one object path.

**Comment by yashBhosale** [comment]
As far as I can tell, the fix is just to change the signature of the signal in the xml, I can make the change and file a pull request for it.

**Comment by alexdelorenzo** [comment]
Good catch, thanks for submitting a pull request. I've merged it with the main branch.
